### PR TITLE
Fpgamatt/subdevid 0001

### PR DESCRIPTION
**Pull request by fpgamatt**
*PR Title should start with one of the following tags: [Fix]/[Feature]/[Style]/[Update]*

*[Fix]- Bug Fix*

*[Feature]- for new feature*

*[Style]- Grammar or branding fix*

*[Update]-For an update to an existing feature*

------------- *Keep everything below this line* -------------------------

### Description
*Describe the issue, update, change or fix and **why***

### Collateral (docs, reports, design examples, case IDs):

- [ ] Document Update Required? (Specify FIM/AFU/Scripts)

### CODE REVIEW

**Comment by fpgamatt** [comment]
The functionality moved to board_common exists on any board that has qsfp(s) and hssi subsystems.

We could call these boards something like pci_jtag_devkit.

**Comment by michael-adler** [comment]
Can someone please explain why this very invasive change is needed and why something simpler won't work? I see complexity being added both here and to the HW side.

**Comment by fpgamatt** [comment]
I would not classify this change as invasive. We are just adding a new board to the board plug-in framework of opae. This new board is a generic PCI devkit without a board BMC and is jtag only. Without this change, boards were incorrectly identifying themselves, and then opae would in turn mishandle the misidentified board.

**Comment by michael-adler** [comment]
So is the rule: set subdevice ID to 1 if there is no BMC and to 0x1771 if there is a BMC?

**Comment by fpgamatt** [comment]
There are currently quite a few subdevice ids being used. The intent is help identify the board with just lspci, and to address concerns from the kernel community of having just a generic DFL Device id with out any subdevice info. The subdevice of 0x1771 is actually a n6001, and 0x1770 is a n6000. 0x17d4 is used for C6100.

**Comment by fpgamatt** [comment]
can I get an approve so this can be merged into master. The RTL has been merged.

**Comment by michael-adler** [comment]
> can I get an approve so this can be merged into master. The RTL has been merged.

I can't help there. Not a code owner.

**Review by anandaravuri — APPROVED** [review]

**Pull request merged**
