### PR TITLE
fix: remove clx he loopback sub command

### PR DESCRIPTION
**Pull request by anandaravuri**
CXL host exerciser doesn’t support loopback feature, so remove lpbk sub command

### CODE REVIEW

**Review by fpgamatt — COMMENTED** [review]
Please update the commit message as to why loopback sub command is being removed.

**Comment by anandaravuri** [comment]
> Please update the commit message as to why loopback sub command is being removed.

Ananda: updated commit meassge with comments

**Comment by fpgamatt** [comment]
I don't see "CXL host exerciser doesn’t support loopback feature, so remove lpbk sub command" in the commit message. I even pulled your branch locally and checked.

**Review by tswhison — APPROVED** [review]
Thanks for the updated message.

**Pull request merged**
